import {
  FileText,
  Image as ImageIcon,
  FileSpreadsheet,
  FileCode,
  Combine,
  Scissors,
  RotateCw,
  Trash2,
  Minimize2,
  Wrench,
  Search,
  Lock,
  Unlock,
  Stamp,
  Sparkles,
  Languages,
  Wand2,
  ScanLine,
  Mic,
  ArrowRightLeft,
  Edit3,
  Folder,
  Type,
  ImagePlus,
  Highlighter,
  PenTool,
  MessageSquare,
  StickyNote,
  Bookmark,
  Shield,
  EyeOff,
  FileSignature,
  Cloud,
  Link,
  Users,
  Share2,
  Clock,
  Archive,
  Layers,
  Crop
} from 'lucide-react';
import { Tool, ToolCategory, User } from './types';

export const APP_NAME = "𝕻𝖆𝖕𝖊𝖗𝖃";

export const TOOLS: Tool[] = [
  // Create
  { id: 'create-document', name: 'Create Document', description: 'Create a new document from scratch or plain text.', category: ToolCategory.CREATE, icon: FileText, requiredPlan: 'Free' },
  { id: 'create-pdf', name: 'Create PDF', description: 'Generate a new PDF document.', category: ToolCategory.CREATE, icon: FileText, requiredPlan: 'Free' },
  { id: 'resume-builder', name: 'Resume/CV builder', description: 'Build professional resumes.', category: ToolCategory.CREATE, icon: FileText, requiredPlan: 'Plus' },
  { id: 'letter-templates', name: 'Letter/document templates', description: 'Use predefined templates for letters.', category: ToolCategory.CREATE, icon: FileText, requiredPlan: 'Plus' },
  { id: 'invoice-creator', name: 'Invoice creator', description: 'Generate professional invoices.', category: ToolCategory.CREATE, icon: FileText, requiredPlan: 'Max' },
  { id: 'certificate-creator', name: 'Certificate creator', description: 'Design and create certificates.', category: ToolCategory.CREATE, icon: FileText, requiredPlan: 'Max' },
  { id: 'form-creator', name: 'Form creator', description: 'Build interactive forms.', category: ToolCategory.CREATE, icon: FileText, requiredPlan: 'Max' },
  { id: 'camera-scanner', name: 'Camera Scanner', description: 'Scan documents directly via your camera.', category: ToolCategory.CREATE, icon: ScanLine, isPopular: true, requiredPlan: 'Free' },
  { id: 'batch-scanner', name: 'Batch scanner', description: 'Scan multiple pages at once.', category: ToolCategory.CREATE, icon: ScanLine, requiredPlan: 'Max' },
  { id: 'auto-edge-detect', name: 'Auto edge detection', description: 'Automatically detect document edges.', category: ToolCategory.CREATE, icon: Scissors, requiredPlan: 'Free' },
  { id: 'auto-enhance', name: 'Auto enhance', description: 'Automatically adjust brightness and apply filters.', category: ToolCategory.CREATE, icon: Sparkles, requiredPlan: 'Plus' },
  { id: 'deskew', name: 'Deskew', description: 'Straighten scanned documents.', category: ToolCategory.CREATE, icon: Wrench, requiredPlan: 'Max' },

  // Convert
  { id: 'text-to-pdf', name: 'Text → PDF', description: 'Convert plain text to PDF format.', category: ToolCategory.CONVERT, icon: Type, requiredPlan: 'Free' },
  { id: 'word-to-pdf', name: 'Word → PDF', description: 'Convert DOCX files to PDF format.', category: ToolCategory.CONVERT, icon: ArrowRightLeft, requiredPlan: 'Plus' },
  { id: 'excel-to-pdf', name: 'Excel → PDF', description: 'Convert spreadsheets to PDF format.', category: ToolCategory.CONVERT, icon: FileSpreadsheet, requiredPlan: 'Plus' },
  { id: 'powerpoint-to-pdf', name: 'PowerPoint → PDF', description: 'Convert PPTX files to PDF format.', category: ToolCategory.CONVERT, icon: FileText, requiredPlan: 'Plus' },
  { id: 'image-to-pdf', name: 'Image → PDF', description: 'Convert JPG or PNG images to PDF.', category: ToolCategory.CONVERT, icon: ImagePlus, requiredPlan: 'Free' },
  { id: 'pdf-to-word', name: 'PDF → Word', description: 'Convert PDF documents to editable Word files.', category: ToolCategory.CONVERT, icon: FileText, isPopular: true, requiredPlan: 'Plus' },
  { id: 'pdf-to-excel', name: 'PDF → Excel', description: 'Convert PDF tables to Excel spreadsheets.', category: ToolCategory.CONVERT, icon: FileSpreadsheet, requiredPlan: 'Max' },
  { id: 'pdf-to-powerpoint', name: 'PDF → PowerPoint', description: 'Convert PDF to PowerPoint presentations.', category: ToolCategory.CONVERT, icon: FileText, requiredPlan: 'Max' },
  { id: 'pdf-to-text', name: 'PDF → Text', description: 'Extract raw text from PDF documents.', category: ToolCategory.CONVERT, icon: FileText, requiredPlan: 'Free' },
  { id: 'pdf-to-image', name: 'PDF → Image', description: 'Convert PDF pages to images.', category: ToolCategory.CONVERT, icon: ImagePlus, requiredPlan: 'Free' },
  { id: 'html-to-pdf', name: 'HTML → PDF', description: 'Convert web pages to PDF.', category: ToolCategory.CONVERT, icon: FileCode, requiredPlan: 'Max' },
  { id: 'markdown-to-pdf', name: 'Markdown → PDF', description: 'Convert Markdown files to PDF.', category: ToolCategory.CONVERT, icon: FileCode, requiredPlan: 'Max' },

  // Edit
  { id: 'edit-pdf-text', name: 'Edit PDF text', description: 'Edit text inside your PDF.', category: ToolCategory.EDIT, icon: Edit3, isPopular: true, requiredPlan: 'Plus' },
  { id: 'edit-images', name: 'Edit images', description: 'Modify images inside your PDF.', category: ToolCategory.EDIT, icon: ImagePlus, requiredPlan: 'Plus' },
  { id: 'add-text', name: 'Add text', description: 'Insert new text into the PDF.', category: ToolCategory.EDIT, icon: Type, requiredPlan: 'Free' },
  { id: 'add-shapes', name: 'Add shapes', description: 'Draw basic shapes.', category: ToolCategory.EDIT, icon: Edit3, requiredPlan: 'Plus' },
  { id: 'draw-freehand', name: 'Draw/freehand', description: 'Freehand draw on your PDF.', category: ToolCategory.EDIT, icon: PenTool, requiredPlan: 'Free' },
  { id: 'highlight-pdf', name: 'Highlight', description: 'Highlight important text.', category: ToolCategory.EDIT, icon: Highlighter, requiredPlan: 'Free' },
  { id: 'underline-pdf', name: 'Underline', description: 'Underline text.', category: ToolCategory.EDIT, icon: Edit3, requiredPlan: 'Free' },
  { id: 'strikethrough-pdf', name: 'Strikethrough', description: 'Strike through text.', category: ToolCategory.EDIT, icon: Edit3, requiredPlan: 'Plus' },
  { id: 'whiteout-redact', name: 'Whiteout/redact', description: 'Hide sensitive information.', category: ToolCategory.EDIT, icon: EyeOff, requiredPlan: 'Max' },
  { id: 'add-links', name: 'Add links', description: 'Insert clickable hyperlinks.', category: ToolCategory.EDIT, icon: Link, requiredPlan: 'Max' },
  { id: 'crop-pages', name: 'Crop pages', description: 'Crop page margins.', category: ToolCategory.EDIT, icon: Crop, requiredPlan: 'Plus' },
  { id: 'resize-pages', name: 'Resize pages', description: 'Change page dimensions.', category: ToolCategory.EDIT, icon: Wrench, requiredPlan: 'Max' },
  { id: 'change-background', name: 'Change page background', description: 'Alter page background color or image.', category: ToolCategory.EDIT, icon: ImagePlus, requiredPlan: 'Max' },
  { id: 'rearrange-pages-edit', name: 'Rearrange pages', description: 'Reorder pages visually.', category: ToolCategory.EDIT, icon: RotateCw, requiredPlan: 'Plus' },

  // Organize
  { id: 'merge-pdf', name: 'Merge PDF', description: 'Combine multiple PDFs into one unified document.', category: ToolCategory.ORGANIZE, icon: Combine, isPopular: true, requiredPlan: 'Free' },
  { id: 'split-pdf', name: 'Split PDF', description: 'Separate one page or a whole set for easy conversion.', category: ToolCategory.ORGANIZE, icon: Scissors, requiredPlan: 'Free' },
  { id: 'extract-pages', name: 'Extract pages', description: 'Extract specific pages from a PDF.', category: ToolCategory.ORGANIZE, icon: Scissors, requiredPlan: 'Free' },
  { id: 'delete-pages', name: 'Delete pages', description: 'Remove unwanted pages.', category: ToolCategory.ORGANIZE, icon: Trash2, requiredPlan: 'Free' },
  { id: 'duplicate-pages', name: 'Duplicate pages', description: 'Create copies of specific pages.', category: ToolCategory.ORGANIZE, icon: FileText, requiredPlan: 'Max' },
  { id: 'rotate-pages', name: 'Rotate pages', description: 'Rotate pages to the correct orientation.', category: ToolCategory.ORGANIZE, icon: RotateCw, requiredPlan: 'Free' },
  { id: 'reorder-pages', name: 'Reorder pages', description: 'Change the order of pages.', category: ToolCategory.ORGANIZE, icon: RotateCw, requiredPlan: 'Free' },
  { id: 'pdf-organizer', name: 'PDF Organizer', description: 'Visually organize all pages.', category: ToolCategory.ORGANIZE, icon: Folder, requiredPlan: 'Plus' },
  { id: 'insert-pages', name: 'Insert pages', description: 'Add new pages into a PDF.', category: ToolCategory.ORGANIZE, icon: FileText, requiredPlan: 'Max' },
  { id: 'replace-pages', name: 'Replace pages', description: 'Swap pages with new ones.', category: ToolCategory.ORGANIZE, icon: FileText, requiredPlan: 'Max' },
  { id: 'add-blank-pages', name: 'Add blank pages', description: 'Insert empty pages.', category: ToolCategory.ORGANIZE, icon: FileText, requiredPlan: 'Max' },

  // OCR & AI
  { id: 'ocr-pdf', name: 'Basic OCR', description: 'Make scanned documents searchable and selectable.', category: ToolCategory.OPTIMIZE, icon: Search, requiredPlan: 'Free' },
  { id: 'image-to-text', name: 'Image → Text', description: 'Extract text from images.', category: ToolCategory.OPTIMIZE, icon: FileText, requiredPlan: 'Free' },
  { id: 'pdf-to-searchable-pdf', name: 'PDF → searchable PDF', description: 'Convert scanned PDFs to searchable PDFs.', category: ToolCategory.OPTIMIZE, icon: Search, requiredPlan: 'Plus' },
  { id: 'handwriting-recognition', name: 'Handwriting recognition', description: 'Convert handwriting to text.', category: ToolCategory.OPTIMIZE, icon: FileText, requiredPlan: 'Max' },
  { id: 'summarize-pdf', name: 'Summarize PDF', description: 'Get a quick summary of your document.', category: ToolCategory.OPTIMIZE, icon: Sparkles, requiredPlan: 'Max' },
  { id: 'ask-questions', name: 'Ask questions about PDF', description: 'Chat with your document.', category: ToolCategory.OPTIMIZE, icon: MessageSquare, requiredPlan: 'Max' },
  { id: 'extract-tables', name: 'Extract tables', description: 'Pull tabular data from PDFs.', category: ToolCategory.OPTIMIZE, icon: FileSpreadsheet, requiredPlan: 'Max' },
  { id: 'extract-images', name: 'Extract images', description: 'Save images embedded in PDFs.', category: ToolCategory.OPTIMIZE, icon: ImagePlus, requiredPlan: 'Max' },
  { id: 'translate-document', name: 'Translate document', description: 'Translate PDF to another language.', category: ToolCategory.OPTIMIZE, icon: Languages, requiredPlan: 'Max' },
  { id: 'rewrite-text', name: 'Rewrite text', description: 'Improve or rewrite text sections.', category: ToolCategory.OPTIMIZE, icon: Wand2, requiredPlan: 'Max' },
  { id: 'grammar-correction', name: 'Grammar correction', description: 'Fix grammatical errors in the text.', category: ToolCategory.OPTIMIZE, icon: Edit3, requiredPlan: 'Max' },

  // Optimize
  { id: 'compress-pdf', name: 'Basic PDF Compression', description: 'Reduce file size while optimizing for maximal PDF quality.', category: ToolCategory.OPTIMIZE, icon: Minimize2, isPopular: true, requiredPlan: 'Free' },
  { id: 'optimize-pdf', name: 'Optimize PDF', description: 'General optimization for web and print.', category: ToolCategory.OPTIMIZE, icon: Minimize2, requiredPlan: 'Plus' },
  { id: 'convert-to-pdfa', name: 'Convert to PDF/A', description: 'Convert to long-term archiving format.', category: ToolCategory.OPTIMIZE, icon: Archive, requiredPlan: 'Max' },
  { id: 'flatten-pdf', name: 'Flatten PDF', description: 'Flatten layers and annotations.', category: ToolCategory.OPTIMIZE, icon: Layers, requiredPlan: 'Max' },
  { id: 'remove-metadata', name: 'Remove metadata', description: 'Strip document properties and personal info.', category: ToolCategory.OPTIMIZE, icon: EyeOff, requiredPlan: 'Max' },
  { id: 'reduce-image-size', name: 'Reduce image size', description: 'Downsample images inside the PDF.', category: ToolCategory.OPTIMIZE, icon: Minimize2, requiredPlan: 'Free' },
  { id: 'batch-compression', name: 'Batch compression', description: 'Compress multiple files at once.', category: ToolCategory.OPTIMIZE, icon: Layers, requiredPlan: 'Max' },

  // Security
  { id: 'protect-pdf', name: 'Password protect', description: 'Add a password to protect your PDF.', category: ToolCategory.SECURITY, icon: Lock, requiredPlan: 'Free' },
  { id: 'remove-password', name: 'Remove PDF password when authorized', description: 'Remove password protection if authorized.', category: ToolCategory.SECURITY, icon: Unlock, requiredPlan: 'Max' },
  { id: 'encrypt-files', name: 'Encrypt files', description: 'Securely encrypt your sensitive files.', category: ToolCategory.SECURITY, icon: Shield, requiredPlan: 'Max' },
  { id: 'redact-info', name: 'Redact sensitive information', description: 'Permanently remove visible text/images.', category: ToolCategory.SECURITY, icon: EyeOff, requiredPlan: 'Max' },
  { id: 'digital-signatures', name: 'Digital signatures', description: 'Sign your documents digitally.', category: ToolCategory.SECURITY, icon: FileSignature, requiredPlan: 'Max' },
  { id: 'signature-requests', name: 'Signature requests', description: 'Send documents for others to sign.', category: ToolCategory.SECURITY, icon: FileSignature, requiredPlan: 'Max' },
  { id: 'private-folder', name: 'Private folder', description: 'Hide and secure your private documents.', category: ToolCategory.SECURITY, icon: EyeOff, requiredPlan: 'Plus' },
  { id: 'secure-sharing', name: 'Secure sharing', description: 'Share documents securely.', category: ToolCategory.SECURITY, icon: Share2, requiredPlan: 'Max' },
  { id: 'expiring-links', name: 'Expiring share links', description: 'Create share links that expire automatically.', category: ToolCategory.SECURITY, icon: Clock, requiredPlan: 'Max' }
];

export const MOCK_USER: User = {
  id: 'u_123456789',
  uid: 'u_123456789',
  name: 'Alex Sterling',
  email: 'alex.sterling@paperx.io',
  avatarUrl: 'https://picsum.photos/200/200',
  plan: 'Basic Plan',
  memberSince: 'Sep 2023',
  projectsUsed: 2,  
  maxProjects: 5
};
