import React, { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  X, 
  Send, 
  ArrowLeft, 
  Copy, 
  Headset, 
  Sparkles, 
  MessageSquare, 
  Bot, 
  Check, 
  CheckCheck,
  Search, 
  ChevronRight, 
  ChevronDown,
  Zap, 
  CreditCard, 
  FileText, 
  UserCheck, 
  Mail, 
  ShieldCheck, 
  Clock, 
  AlertCircle, 
  PlusCircle, 
  Paperclip, 
  Smile, 
  RotateCcw,
  ExternalLink,
  LifeBuoy
} from 'lucide-react';
import { doc, onSnapshot, setDoc, updateDoc, arrayUnion } from 'firebase/firestore';
import { db } from '../services/firebase';
import { User } from '../types';

export interface SupportChatProps {
  isOpen: boolean;
  onClose: () => void;
  user: User | null;
  initialTopic?: string;
  onSessionStatusChange?: (hasOngoingChat: boolean) => void;
}

interface ChatMessage {
  id?: string;
  type: 'user' | 'bot' | 'admin' | 'system';
  text: string;
  time: string;
  timestamp?: number;
  isSystemNotice?: boolean;
  attachment?: string;
}

interface QuickTopic {
  id: string;
  icon: React.ReactNode;
  category: string;
  title: string;
  subtitle: string;
  query: string;
  botAnswer: string;
}

interface SupportSessionData {
  sessionId: string;
  chatId: string;
  status: 'active' | 'closed';
  closedReason?: 'inactivity_timeout' | 'user_closed' | 'admin_resolved';
  closedAt?: number;
  createdAt: number;
  lastUserActivity: number;
}

const INACTIVITY_TIMEOUT_MS = 10 * 60 * 1000; // 10 minutes

const QUICK_TOPICS: QuickTopic[] = [
  {
    id: 'payment_approval',
    icon: <CreditCard size={15} className="text-amber-500" />,
    category: 'Billing & Plans',
    title: 'Verify 12-Digit UTR',
    subtitle: 'Check UPI approval or speed up verification',
    query: 'I completed payment via UPI QR code. Please verify my 12-digit UTR reference and approve my membership.',
    botAnswer: '⚡ **Payment & Membership Verification**\n\n• Thank you for subscribing! Your verification request is queued with priority.\n• The PaperX verification desk matches your 12-digit bank UTR reference within 5–10 minutes.\n• Once verified, your account tier upgrades automatically across all your devices.\n\n💬 Feel free to paste your 12-digit UTR number or attach the transaction receipt here!'
  },
  {
    id: 'limits_files',
    icon: <Zap size={15} className="text-blue-500" />,
    category: 'Limits & Performance',
    title: 'File & Page Limits',
    subtitle: '500MB batch limit & upload rules',
    query: 'What are the file size and page limits for conversions and batch processing?',
    botAnswer: '📄 **PaperX Processing Limits**\n\n• **Free Tier**: Up to 50MB per file, 100 pages per conversion.\n• **Plus & Max Plans**: Up to 500MB per file, unlimited pages & priority high-speed parallel queues.\n• **Tip**: Make sure your file is not password-encrypted before converting.'
  },
  {
    id: 'ocr_tools',
    icon: <FileText size={15} className="text-emerald-500" />,
    category: 'Features',
    title: 'OCR & Text Extraction',
    subtitle: 'Extract text from scanned PDFs & images',
    query: 'How do I extract text from scanned documents or translate PDFs accurately?',
    botAnswer: '🔍 **OCR & Text Extraction Guide**\n\n• Use our **OCR / Extract Text** tool for image and PDF scans.\n• For sharpest precision, upload clean scans at 300 DPI with standard orientation.\n• PaperX supports 40+ global languages with automated script detection.'
  },
  {
    id: 'human_officer',
    icon: <UserCheck size={15} className="text-purple-500" />,
    category: 'Live Support',
    title: 'Talk to Live Specialist',
    subtitle: 'Connect directly with on-duty operations team',
    query: 'I need assistance from a live customer support specialist.',
    botAnswer: '👨‍💼 **Live Specialist Dispatched**\n\n• A direct priority notification has been sent to our on-duty support operations desk.\n• PaperX Team will review your account details and reply in this thread shortly.\n• Replies are saved in real-time — feel free to write down any specific questions!'
  }
];

const FAQS = [
  {
    category: "Billing & Plans",
    q: "How do I upgrade or activate my subscription?",
    a: "Navigate to Profile > Billing & Plans, select your preferred plan (Plus or Max), make a payment via the official UPI QR code, and submit your 12-digit bank UTR reference. Verification completes automatically within 10 minutes."
  },
  {
    category: "Billing & Plans",
    q: "What is the 12-digit UTR and where can I find it?",
    a: "A UTR (Unique Transaction Reference) is a 12-digit number generated by your bank or UPI app (Google Pay, PhonePe, Paytm, CRED, BHIM) after a successful transfer. You can find it in the transaction receipt or payment details screen."
  },
  {
    category: "Billing & Plans",
    q: "Why is my payment showing pending or unverified?",
    a: "Bank settlements and automatic matching typically take 5–10 minutes. Please ensure your 12-digit UTR reference was entered accurately without spaces. You can also paste your UTR directly in this support chat for immediate manual verification."
  },
  {
    category: "Billing & Plans",
    q: "What happens if money was debited but the order is not approved?",
    a: "Do not worry! In UPI transactions, if money leaves your bank account, it is fully secured. Simply message us here with your 12-digit UTR reference and registered email. PaperX Team will instantly cross-check with the banking desk and activate your Pro tier."
  },
  {
    category: "Billing & Plans",
    q: "Can I get an official invoice or GST receipt?",
    a: "Yes! For business or GST-compliant tax invoices, email paperx.assist@gmail.com with your registered email, company name, GSTIN, and Order ID. Our billing desk issues verified invoices within 24 hours."
  },
  {
    category: "Billing & Plans",
    q: "What happens when my subscription expires?",
    a: "When your subscription period ends, your account smoothly transitions to the Free tier. None of your stored documents are deleted, but free tier processing limits (50MB / 100 pages per file) will apply."
  },
  {
    category: "Billing & Plans",
    q: "What is your refund policy?",
    a: "We offer a 100% full refund within 48 hours of purchase if you experience technical issues that our support team cannot resolve. Contact us via chat or email paperx.assist@gmail.com with your Order ID."
  },
  {
    category: "File Processing",
    q: "What file formats does PaperX support?",
    a: "PaperX natively supports PDF, DOC/DOCX, XLS/XLSX, PPT/PPTX, PNG, JPG, JPEG, WebP, TIFF, TXT, CSV, SVG, and EPUB files for conversions, compression, watermarking, and text extraction."
  },
  {
    category: "File Processing",
    q: "What are the file size and page limits?",
    a: "• Free Tier: Up to 50MB per file and 100 pages per conversion.\n• Plus Tier: Up to 250MB per file with unlimited pages.\n• Max Tier: Up to 500MB per file with parallel batch engine and priority fast queues."
  },
  {
    category: "File Processing",
    q: "How does batch file conversion work?",
    a: "You can drag and drop multiple files at once into any conversion tool. PaperX processes files simultaneously and lets you download individual files or a single consolidated ZIP archive."
  },
  {
    category: "File Processing",
    q: "How do I compress large PDF documents without losing quality?",
    a: "Use our Compress PDF tool. Choose between 'Balanced Compression' (maintains crisp vector text and sharp graphics) and 'High Compression' (maximizes file size reduction for email attachments)."
  },
  {
    category: "File Processing",
    q: "Can PaperX process password-protected PDFs?",
    a: "Yes. Use our Unlock PDF tool and enter your document password when prompted. Once unlocked, you can freely convert, merge, split, or edit your document."
  },
  {
    category: "OCR & Tools",
    q: "How does Optical Character Recognition (OCR) work?",
    a: "Our neural OCR engine inspects pixel data inside scanned documents or photos, accurately recognizing letters, tables, and formatting to output fully searchable and editable text (TXT, DOCX, or searchable PDF)."
  },
  {
    category: "OCR & Tools",
    q: "What languages are supported for OCR and document translation?",
    a: "PaperX supports over 40 global languages including English, Hindi, Spanish, French, German, Japanese, Chinese, Arabic, Russian, and Portuguese with automatic script detection."
  },
  {
    category: "OCR & Tools",
    q: "Can I add e-signatures or custom watermarks?",
    a: "Yes! Use the Sign & Protect tool to draw or upload your signature, or add custom text and image watermarks with controllable opacity, font style, and angle."
  },
  {
    category: "Security & Privacy",
    q: "Are my uploaded documents secure and confidential?",
    a: "Yes. All data transmissions are encrypted with TLS 1.3, and data at rest uses AES-256 enterprise encryption. We adhere strictly to zero-knowledge processing standards."
  },
  {
    category: "Security & Privacy",
    q: "How long are uploaded files stored on servers?",
    a: "Temporary processing files are automatically and permanently erased from conversion clusters after processing. Persistent files are stored only within your private account workspace."
  },
  {
    category: "Security & Privacy",
    q: "Does PaperX train AI models on user documents?",
    a: "No. PaperX never uses, scans, sells, or trains public AI models on any of your uploaded files or confidential documents."
  },
  {
    category: "Troubleshooting",
    q: "What should I do if a conversion fails or gets stuck?",
    a: "1. Verify that your file is not corrupted or password-locked.\n2. Ensure the file is under your tier's size limit.\n3. Try converting one file at a time or refresh your browser.\n4. Open Live Chat to connect with our technical engineers for instant assistance."
  },
  {
    category: "Troubleshooting",
    q: "How do I reach a human support specialist?",
    a: "Open the Live Chat tab and send your query, or select 'Talk to Live Specialist'. You can also email paperx.assist@gmail.com for priority email support."
  }
];

// Helper to render text with bold and bullet highlights cleanly
const formatMessageText = (text: string) => {
  if (!text) return null;
  const lines = text.split('\n');
  return lines.map((line, idx) => {
    const parts = line.split(/(\*\*.*?\*\*)/g);
    return (
      <span key={idx} className="block leading-relaxed">
        {parts.map((part, pIdx) => {
          if (part.startsWith('**') && part.endsWith('**')) {
            return (
              <strong key={pIdx} className="font-semibold text-stone-900 dark:text-white">
                {part.slice(2, -2)}
              </strong>
            );
          }
          return part;
        })}
      </span>
    );
  });
};

const EMOJIS = ['👋', '⚡', '👍', '🙏', '📄', '✅', '❤️', '🔥', '😊', '💳'];

export const SupportChat: React.FC<SupportChatProps> = ({ 
  isOpen, 
  onClose, 
  user, 
  initialTopic, 
  onSessionStatusChange 
}) => {
  const [activeTab, setActiveTab] = useState<'chat' | 'faqs'>('chat');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [copiedEmail, setCopiedEmail] = useState(false);
  const [faqSearch, setFaqSearch] = useState('');
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null);
  const [selectedFaqCategory, setSelectedFaqCategory] = useState<string>('All');
  const [copiedMsgId, setCopiedMsgId] = useState<string | null>(null);
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);
  const [attachmentData, setAttachmentData] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Inactivity & Session Management States
  const [chatSession, setChatSession] = useState<SupportSessionData | null>(null);
  const [isClosed, setIsClosed] = useState<boolean>(false);
  const [closedReason, setClosedReason] = useState<string | null>(null);
  const [lastUserActivityTime, setLastUserActivityTime] = useState<number>(Date.now());

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const getStorageKey = useCallback(() => {
    return user?.uid ? `paperx_support_session_user_${user.uid}` : `paperx_support_session_guest`;
  }, [user?.uid]);

  // Synchronize active ongoing chat status to parent and local storage
  useEffect(() => {
    const hasOngoing = !isClosed && chatSession?.status === 'active' && messages.length > 0 && (Date.now() - lastUserActivityTime < INACTIVITY_TIMEOUT_MS);
    if (onSessionStatusChange) {
      onSessionStatusChange(hasOngoing);
    }
    try {
      const key = getStorageKey();
      const raw = localStorage.getItem(key);
      if (raw) {
        const session = JSON.parse(raw);
        session.hasOngoingMessages = hasOngoing;
        session.hasUserStartedChat = messages.length > 0;
        session.status = isClosed ? 'closed' : session.status;
        localStorage.setItem(key, JSON.stringify(session));
      }
      window.dispatchEvent(new CustomEvent('paperx-support-session-update', { detail: { hasOngoing } }));
    } catch (e) {}
  }, [messages.length, isClosed, chatSession?.status, lastUserActivityTime, onSessionStatusChange, getStorageKey]);

  const generateNewSession = useCallback((reasonToReset?: string): SupportSessionData => {
    const now = Date.now();
    const newSessionId = `${now.toString(36)}_${Math.random().toString(36).substring(2, 7)}`;
    const baseId = user?.uid ? `user_${user.uid}` : `guest_${Math.random().toString(36).substring(2, 8)}`;
    const newChatId = `${baseId}_${newSessionId}`;

    const sessionData: SupportSessionData = {
      sessionId: newSessionId,
      chatId: newChatId,
      status: 'active',
      createdAt: now,
      lastUserActivity: now
    };

    try {
      localStorage.setItem(getStorageKey(), JSON.stringify(sessionData));
    } catch (e) {
      console.warn("Storage write note:", e);
    }

    setChatSession(sessionData);
    setIsClosed(false);
    setClosedReason(null);
    setLastUserActivityTime(now);
    setMessages([]);
    return sessionData;
  }, [user?.uid, getStorageKey]);

  // Initialize or resume chat session when modal opens
  useEffect(() => {
    if (!isOpen) return;

    const storageKey = getStorageKey();
    let currentSession: SupportSessionData | null = null;

    try {
      const raw = localStorage.getItem(storageKey);
      if (raw) {
        currentSession = JSON.parse(raw);
      }
    } catch (e) {
      currentSession = null;
    }

    if (!currentSession) {
      currentSession = generateNewSession('initial');
    } else if (currentSession.status === 'closed') {
      currentSession = generateNewSession('previous_closed');
    } else {
      const elapsed = Date.now() - (currentSession.lastUserActivity || currentSession.createdAt || 0);
      if (elapsed >= INACTIVITY_TIMEOUT_MS) {
        currentSession.status = 'closed';
        currentSession.closedReason = 'inactivity_timeout';
        currentSession.closedAt = Date.now();
        try {
          localStorage.setItem(storageKey, JSON.stringify(currentSession));
        } catch (e) {}

        setChatSession(currentSession);
        setIsClosed(true);
        setClosedReason('inactivity_timeout');
        setLastUserActivityTime(currentSession.lastUserActivity || Date.now());
      } else {
        setChatSession(currentSession);
        setIsClosed(false);
        setClosedReason(null);
        setLastUserActivityTime(currentSession.lastUserActivity || Date.now());
      }
    }
  }, [isOpen, getStorageKey, generateNewSession]);

  const activeChatId = chatSession?.chatId || (user?.uid ? `user_${user.uid}` : `guest_temp`);
  const currentUserId = user?.id || user?.uid || (chatSession?.chatId || 'guest');
  const currentUserName = user?.name || (user?.uid ? `User ${user.uid.substring(0, 5)}` : `Guest User`);
  const currentUserEmail = user?.email || 'Guest User';

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  // Real-time Firestore subscription to active support_chats thread
  useEffect(() => {
    if (!isOpen || !chatSession?.chatId) return;

    const chatRef = doc(db, 'support_chats', chatSession.chatId);
    const unsubscribe = onSnapshot(chatRef, (snapshot) => {
      if (snapshot.exists()) {
        const data = snapshot.data();
        
        if (data?.status === 'closed' && !isClosed) {
          setIsClosed(true);
          setClosedReason(data?.closedReason || 'admin_resolved');
        }

        if (data?.messages && Array.isArray(data.messages)) {
          const formatted: ChatMessage[] = data.messages.map((m: any, idx: number) => ({
            id: m.id || `msg_${idx}`,
            type: m.sender === 'user' ? 'user' : (m.sender === 'system' ? 'system' : (m.sender === 'admin' ? 'admin' : 'bot')),
            text: m.text,
            time: m.timestamp 
              ? new Date(m.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) 
              : new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            timestamp: m.timestamp || Date.now(),
            isSystemNotice: m.sender === 'system' || m.isSystemNotice === true,
            attachment: m.attachment
          }));

          setMessages(formatted);

          const userMsgs = data.messages.filter((m: any) => m.sender === 'user');
          if (userMsgs.length > 0) {
            const lastUserMsg = userMsgs[userMsgs.length - 1];
            if (lastUserMsg.timestamp) {
              setLastUserActivityTime(lastUserMsg.timestamp);
            }
          }

          const lastMsg = data.messages[data.messages.length - 1];
          if (lastMsg && (lastMsg.sender === 'bot' || lastMsg.sender === 'admin')) {
            setIsTyping(false);
          }
        }

        if (data?.unreadByUser) {
          updateDoc(chatRef, { unreadByUser: false }).catch(() => {});
        }
      }
    }, (err) => {
      console.warn("Support chat snapshot notice:", err);
    });

    return () => unsubscribe();
  }, [isOpen, chatSession?.chatId, isClosed]);

  // Real-time 10-minute Inactivity Detection Interval
  useEffect(() => {
    if (!isOpen || isClosed || !chatSession || messages.length === 0) return;

    const interval = setInterval(() => {
      const now = Date.now();
      const elapsed = now - lastUserActivityTime;

      if (elapsed >= INACTIVITY_TIMEOUT_MS) {
        setIsClosed(true);
        setClosedReason('inactivity_timeout');

        const updatedSession: SupportSessionData = {
          ...chatSession,
          status: 'closed',
          closedReason: 'inactivity_timeout',
          closedAt: now
        };
        setChatSession(updatedSession);

        try {
          localStorage.setItem(getStorageKey(), JSON.stringify(updatedSession));
        } catch (e) {}

        const systemNoticeMsg = {
          id: `msg_sys_${now}`,
          sender: 'system',
          senderName: 'System Notice',
          text: '⏱️ This chat session has been closed due to 10 minutes of inactivity.',
          timestamp: now,
          isSystemNotice: true
        };

        setMessages(prev => [
          ...prev,
          {
            id: systemNoticeMsg.id,
            type: 'system',
            text: systemNoticeMsg.text,
            time: new Date(now).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            timestamp: now,
            isSystemNotice: true
          }
        ]);

        if (chatSession.chatId) {
          const chatRef = doc(db, 'support_chats', chatSession.chatId);
          updateDoc(chatRef, {
            status: 'closed',
            closedReason: 'inactivity_timeout',
            closedAt: now,
            messages: arrayUnion(systemNoticeMsg),
            lastMessage: 'Chat closed due to 10 minutes of inactivity'
          }).catch((e) => {
            console.warn("Firestore status update notice:", e);
          });
        }
      }
    }, 5000);

    return () => clearInterval(interval);
  }, [isOpen, isClosed, chatSession, lastUserActivityTime, messages.length, getStorageKey]);

  useEffect(() => {
    if (isOpen && activeTab === 'chat') {
      scrollToBottom();
    }
  }, [messages, isTyping, isOpen, activeTab]);

  const notifyAdmin = async (queryText: string, targetChatId: string, hasBotAnswer: boolean = false) => {
    try {
      await fetch('/api/admin/support/notify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId: currentUserId,
          userName: currentUserName,
          userEmail: currentUserEmail,
          query: queryText,
          chatId: targetChatId,
          hasBotAnswer
        })
      });
    } catch (err) {
      console.warn("Support dispatch notification note:", err);
    }
  };

  const handleStartNewChat = () => {
    generateNewSession('manual_new');
    setActiveTab('chat');
  };

  const handleSendMessage = async (textToSend?: string, predefinedBotAnswer?: string) => {
    const text = (textToSend || inputValue).trim();
    if (!text && !attachmentData) return;

    let targetSession = chatSession;
    if (isClosed || !targetSession || targetSession.status === 'closed') {
      targetSession = generateNewSession('send_message_reset');
    }

    const now = Date.now();
    setInputValue('');
    setShowEmojiPicker(false);
    const attachmentToSent = attachmentData;
    setAttachmentData(null);
    setLastUserActivityTime(now);

    if (targetSession) {
      const updated = {
        ...targetSession,
        lastUserActivity: now,
        status: 'active' as const
      };
      setChatSession(updated);
      try {
        localStorage.setItem(getStorageKey(), JSON.stringify(updated));
      } catch (e) {}
    }
    
    if (activeTab !== 'chat') {
      setActiveTab('chat');
    }

    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
    }

    const msgId = `msg_${now}_${Math.random().toString(36).substring(2, 6)}`;
    const userMsg: any = {
      id: msgId,
      sender: 'user',
      senderName: currentUserName,
      text,
      timestamp: now
    };
    if (attachmentToSent) {
      userMsg.attachment = attachmentToSent;
    }

    const localFormatted: ChatMessage = {
      id: msgId,
      type: 'user',
      text,
      time: new Date(now).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      timestamp: now,
      attachment: attachmentToSent || undefined
    };

    setMessages(prev => [...prev, localFormatted]);

    const destinationChatId = targetSession?.chatId || activeChatId;

    notifyAdmin(text + (attachmentToSent ? ' [Attachment sent]' : ''), destinationChatId, !!predefinedBotAnswer);
    if (!predefinedBotAnswer) {
      setIsTyping(true);
    }

    try {
      const chatRef = doc(db, 'support_chats', destinationChatId);
      await setDoc(chatRef, {
        chatId: destinationChatId,
        userId: currentUserId,
        userName: currentUserName,
        userEmail: currentUserEmail,
        messages: arrayUnion(userMsg),
        lastMessage: text,
        updatedAt: now,
        status: 'active',
        lastUserActivity: now,
        unreadByAdmin: true,
        unreadByUser: false
      }, { merge: true });

      if (predefinedBotAnswer) {
        setIsTyping(true);
        setTimeout(async () => {
          const botNow = Date.now();
          const botMsg = {
            id: `msg_bot_${botNow}`,
            sender: 'bot',
            senderName: 'PaperX Assistant',
            text: predefinedBotAnswer,
            timestamp: botNow
          };
          try {
            await updateDoc(chatRef, {
              messages: arrayUnion(botMsg),
              lastMessage: predefinedBotAnswer,
              updatedAt: botNow
            });
          } catch (e) {
            console.warn("Support automated reply note:", e);
          }
          setIsTyping(false);
        }, 600);
      }
    } catch (err) {
      console.warn("Support message sync note:", err);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const handleTextareaInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setInputValue(e.target.value);
    setLastUserActivityTime(Date.now());
    e.target.style.height = 'auto';
    e.target.style.height = `${Math.min(e.target.scrollHeight, 120)}px`;
  };

  const copyEmail = () => {
    navigator.clipboard.writeText('paperx.assist@gmail.com');
    setCopiedEmail(true);
    setTimeout(() => setCopiedEmail(false), 2000);
  };

  const copyMessageText = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedMsgId(id);
    setTimeout(() => setCopiedMsgId(null), 1800);
  };

  const insertEmoji = (emoji: string) => {
    setInputValue(prev => prev + emoji);
    setLastUserActivityTime(Date.now());
    setShowEmojiPicker(false);
    if (textareaRef.current) {
      textareaRef.current.focus();
    }
  };

  const faqCategories = ['All', 'Billing & Plans', 'File Processing', 'OCR & Tools', 'Security & Privacy', 'Troubleshooting'];

  const filteredFaqs = FAQS.filter(faq => {
    const matchesCategory = selectedFaqCategory === 'All' || faq.category === selectedFaqCategory;
    const query = faqSearch.toLowerCase();
    const matchesSearch = !query || 
      faq.q.toLowerCase().includes(query) || 
      faq.a.toLowerCase().includes(query) ||
      faq.category.toLowerCase().includes(query);
    return matchesCategory && matchesSearch;
  });

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      setAttachmentData(event.target?.result as string);
      setLastUserActivityTime(Date.now());
    };
    reader.readAsDataURL(file);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const clearAttachment = () => {
    setAttachmentData(null);
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div 
        id="support-chat-backdrop"
        className="fixed inset-0 z-[90] bg-stone-950/40 backdrop-blur-xs flex items-end sm:items-auto justify-center sm:justify-end"
        onClick={onClose}
      >
        <motion.div
          id="support-chat-container"
          initial={{ opacity: 0, y: 25, scale: 0.98 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 25, scale: 0.98 }}
          transition={{ duration: 0.2, ease: [0.16, 1, 0.3, 1] }}
          onClick={(e) => e.stopPropagation()}
          className="fixed inset-x-0 bottom-0 sm:inset-auto sm:bottom-6 sm:right-6 w-full sm:w-[440px] h-[92dvh] sm:h-[680px] sm:max-h-[88vh] bg-white dark:bg-stone-900 rounded-t-[28px] sm:rounded-3xl shadow-[0_25px_80px_-15px_rgba(0,0,0,0.4)] border border-stone-200/90 dark:border-stone-800 flex flex-col overflow-hidden select-text"
        >
          {/* ================= HEADER BAR ================= */}
          <div className="relative px-5 py-3.5 bg-white dark:bg-stone-900 border-b border-stone-200/80 dark:border-stone-800 flex items-center justify-between flex-shrink-0 z-10">
            <div className="flex items-center gap-3">
              <div className="relative">
                <div className="w-9 h-9 rounded-2xl bg-stone-900 text-white dark:bg-white dark:text-stone-900 flex items-center justify-center font-heading font-black text-xs shadow-xs tracking-tighter">
                  P<span className="text-amber-400 dark:text-amber-500">X</span>
                </div>
                <span className="absolute -bottom-0.5 -right-0.5 w-3 h-3 rounded-full bg-emerald-500 ring-2 ring-white dark:ring-stone-900" />
              </div>
              
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="font-heading font-black text-sm text-stone-900 dark:text-white tracking-tight">PaperX Support</h3>
                  <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[9px] font-bold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                    Live
                  </span>
                </div>
                <p className="text-[11px] text-stone-400 font-medium">Operations desk • ~5 min response</p>
              </div>
            </div>

            {/* Header Right Actions & Tab Switcher */}
            <div className="flex items-center gap-1.5">
              <div className="flex items-center p-0.5 bg-stone-100 dark:bg-stone-800 rounded-xl border border-stone-200/60 dark:border-stone-700/60 mr-1">
                <button
                  id="tab-chat-btn"
                  onClick={() => setActiveTab('chat')}
                  className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                    activeTab === 'chat'
                      ? 'bg-white dark:bg-stone-900 text-stone-900 dark:text-white shadow-2xs'
                      : 'text-stone-500 hover:text-stone-900 dark:text-stone-400 dark:hover:text-white'
                  }`}
                >
                  <MessageSquare size={13} />
                  <span>Chat</span>
                </button>
                <button
                  id="tab-faqs-btn"
                  onClick={() => setActiveTab('faqs')}
                  className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                    activeTab === 'faqs'
                      ? 'bg-white dark:bg-stone-900 text-stone-900 dark:text-white shadow-2xs'
                      : 'text-stone-500 hover:text-stone-900 dark:text-stone-400 dark:hover:text-white'
                  }`}
                >
                  <LifeBuoy size={13} />
                  <span>FAQs</span>
                </button>
              </div>

              <button
                id="support-new-session-header-btn"
                onClick={handleStartNewChat}
                title="Restart chat session"
                className="p-1.5 text-stone-400 hover:text-stone-900 dark:hover:text-white hover:bg-stone-100 dark:hover:bg-stone-800 rounded-xl transition cursor-pointer"
              >
                <RotateCcw size={16} />
              </button>

              <button
                id="support-close-btn"
                onClick={onClose}
                aria-label="Close support"
                className="p-1.5 text-stone-400 hover:text-stone-900 dark:hover:text-white hover:bg-stone-100 dark:hover:bg-stone-800 rounded-xl transition cursor-pointer"
              >
                <X size={18} />
              </button>
            </div>
          </div>

          {/* ================= VIEW CONTAINER ================= */}
          <div className="flex-1 min-h-0 flex flex-col bg-stone-50/50 dark:bg-stone-950">
            {activeTab === 'chat' ? (
              <div className="flex-1 flex flex-col min-h-0">
                {/* Horizontal Quick Suggestions Rail */}
                <div className="px-4 py-2.5 bg-white dark:bg-stone-900 border-b border-stone-200/60 dark:border-stone-800/80 flex items-center gap-2 overflow-x-auto no-scrollbar flex-shrink-0">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-stone-400 flex items-center gap-1 shrink-0">
                    <Sparkles size={11} className="text-amber-500" /> Prompts:
                  </span>
                  {QUICK_TOPICS.map((topic) => (
                    <button
                      key={topic.id}
                      onClick={() => handleSendMessage(topic.query, topic.botAnswer)}
                      className="shrink-0 px-2.5 py-1 rounded-xl bg-stone-100 dark:bg-stone-800 hover:bg-stone-200 dark:hover:bg-stone-700 text-stone-800 dark:text-stone-200 text-xs font-semibold border border-stone-200/70 dark:border-stone-700/70 transition flex items-center gap-1.5 cursor-pointer shadow-2xs active:scale-95"
                    >
                      {topic.icon}
                      <span>{topic.title}</span>
                    </button>
                  ))}
                </div>

                {/* Main Message Stream */}
                <div className="flex-1 overflow-y-auto p-4 sm:p-5 space-y-4 custom-scrollbar">
                  {/* Security Notice Pill */}
                  <div className="text-center my-1">
                    <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[10px] font-medium bg-white dark:bg-stone-900 text-stone-500 dark:text-stone-400 border border-stone-200/80 dark:border-stone-800 shadow-2xs">
                      <ShieldCheck size={12} className="text-emerald-500" />
                      PaperX Support Desk • End-to-End Encrypted
                    </span>
                  </div>

                  {/* Empty Welcome Card */}
                  {messages.length === 0 && (
                    <div className="p-5 rounded-2xl bg-white dark:bg-stone-900 border border-stone-200/80 dark:border-stone-800 shadow-2xs text-center space-y-3 my-auto">
                      <div className="w-12 h-12 rounded-2xl bg-stone-100 dark:bg-stone-800 flex items-center justify-center mx-auto text-stone-900 dark:text-white shadow-xs">
                        <Headset size={22} className="text-stone-800 dark:text-stone-200" />
                      </div>
                      <div>
                        <h4 className="font-heading font-black text-sm text-stone-900 dark:text-white">
                          How can we assist you today?
                        </h4>
                        <p className="text-xs text-stone-500 dark:text-stone-400 max-w-xs mx-auto mt-1 leading-relaxed">
                          Ask about UPI payment verification, 12-digit UTR matching, file conversion limits, or get live assistance.
                        </p>
                      </div>

                      {/* Official Email Copy Box */}
                      <div className="pt-2 border-t border-stone-100 dark:border-stone-800 flex items-center justify-between bg-stone-50 dark:bg-stone-950 p-2.5 rounded-xl text-xs">
                        <span className="font-mono text-stone-600 dark:text-stone-400 text-[11px] truncate">
                          paperx.assist@gmail.com
                        </span>
                        <button
                          onClick={copyEmail}
                          className="px-2.5 py-1 bg-white dark:bg-stone-800 hover:bg-stone-100 dark:hover:bg-stone-700 text-stone-800 dark:text-stone-200 rounded-lg text-[10px] font-bold flex items-center gap-1 border border-stone-200 dark:border-stone-700 transition cursor-pointer"
                        >
                          {copiedEmail ? (
                            <>
                              <Check size={11} className="text-emerald-500" />
                              <span className="text-emerald-600">Copied</span>
                            </>
                          ) : (
                            <>
                              <Copy size={11} />
                              <span>Copy</span>
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  )}

                  {/* Render Message Feed */}
                  {messages.map((msg, idx) => {
                    const isUser = msg.type === 'user';
                    const isSystem = msg.type === 'system' || msg.isSystemNotice;

                    if (isSystem) {
                      return (
                        <div key={msg.id || idx} className="my-2 text-center animate-fade-in">
                          <div className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-stone-100 dark:bg-stone-900 text-stone-600 dark:text-stone-400 border border-stone-200 dark:border-stone-800 text-[11px] font-medium max-w-[90%] shadow-2xs">
                            <AlertCircle size={13} className="shrink-0 text-stone-500" />
                            <span>{msg.text}</span>
                          </div>
                        </div>
                      );
                    }

                    return (
                      <div
                        key={msg.id || idx}
                        className={`flex flex-col ${isUser ? 'items-end' : 'items-start'} group relative`}
                      >
                        <div className="flex items-end gap-2 max-w-[88%]">
                          {!isUser && (
                            <div className="w-6 h-6 rounded-lg bg-stone-900 text-white dark:bg-white dark:text-stone-900 flex items-center justify-center shrink-0 mb-1 shadow-xs text-[10px] font-black font-heading">
                              PX
                            </div>
                          )}

                          <div
                            className={`px-4 py-2.5 text-xs sm:text-[13px] leading-relaxed whitespace-pre-wrap ${
                              isUser
                                ? 'bg-stone-900 text-white dark:bg-white dark:text-stone-900 rounded-2xl rounded-br-xs shadow-xs font-normal'
                                : 'bg-white text-stone-900 dark:bg-stone-900 dark:text-stone-100 rounded-2xl rounded-bl-xs border border-stone-200/80 dark:border-stone-800 shadow-2xs'
                            }`}
                          >
                            {msg.attachment && (
                              <div className="mb-2">
                                <img 
                                  src={msg.attachment} 
                                  alt="attachment" 
                                  className="max-w-[200px] sm:max-w-[240px] rounded-xl border border-stone-200 dark:border-stone-700 shadow-xs" 
                                />
                              </div>
                            )}
                            <div>
                              {formatMessageText(msg.text)}
                            </div>
                          </div>
                        </div>

                        {/* Timestamp and action icons */}
                        <div className={`flex items-center gap-1 mt-1 px-1 text-[10px] text-stone-400 ${isUser ? 'mr-1' : 'ml-8'}`}>
                          <span>{msg.time}</span>
                          {isUser && (
                            <CheckCheck size={12} className="text-stone-400 inline ml-0.5" />
                          )}
                          <button
                            onClick={() => copyMessageText(msg.id || `${idx}`, msg.text)}
                            className="opacity-0 group-hover:opacity-100 transition-opacity ml-1.5 hover:text-stone-700 dark:hover:text-stone-300 cursor-pointer"
                            title="Copy message text"
                          >
                            {copiedMsgId === (msg.id || `${idx}`) ? (
                              <Check size={11} className="text-emerald-500" />
                            ) : (
                              <Copy size={11} />
                            )}
                          </button>
                        </div>
                      </div>
                    );
                  })}

                  {/* Typing Indicator */}
                  {isTyping && (
                    <div className="flex items-end gap-2 max-w-[85%] animate-fade-in">
                      <div className="w-6 h-6 rounded-lg bg-stone-900 text-white dark:bg-white dark:text-stone-900 flex items-center justify-center shrink-0 mb-1 text-[10px] font-black font-heading">
                        PX
                      </div>
                      <div className="px-3.5 py-2 bg-white dark:bg-stone-900 rounded-2xl rounded-bl-xs border border-stone-200/80 dark:border-stone-800 flex items-center gap-1.5 h-8 shadow-2xs">
                        <span className="w-1.5 h-1.5 bg-stone-900 dark:bg-white rounded-full animate-bounce" />
                        <span className="w-1.5 h-1.5 bg-stone-900 dark:bg-white rounded-full animate-bounce [animation-delay:0.15s]" />
                        <span className="w-1.5 h-1.5 bg-stone-900 dark:bg-white rounded-full animate-bounce [animation-delay:0.3s]" />
                      </div>
                    </div>
                  )}

                  <div ref={messagesEndRef} />
                </div>

                {/* Emoji Quick Picker Popup */}
                {showEmojiPicker && (
                  <div className="p-2 bg-white dark:bg-stone-900 border-t border-stone-200 dark:border-stone-800 flex items-center gap-1.5 overflow-x-auto flex-shrink-0 animate-fade-in">
                    {EMOJIS.map((emoji) => (
                      <button
                        key={emoji}
                        type="button"
                        onClick={() => insertEmoji(emoji)}
                        className="p-1.5 hover:bg-stone-100 dark:hover:bg-stone-800 rounded-lg text-base transition cursor-pointer"
                      >
                        {emoji}
                      </button>
                    ))}
                  </div>
                )}

                {/* Chat Input Container */}
                {isClosed ? (
                  <div className="p-3.5 bg-white dark:bg-stone-900 border-t border-stone-200/90 dark:border-stone-800 flex-shrink-0 space-y-2.5">
                    <div className="flex items-start gap-2.5 p-3 rounded-xl bg-stone-50 dark:bg-stone-950 border border-stone-200 dark:border-stone-800 text-stone-800 dark:text-stone-200 text-xs">
                      <Clock size={16} className="text-stone-400 shrink-0 mt-0.5" />
                      <div className="flex-1 min-w-0">
                        <p className="font-bold text-[12px] font-heading text-stone-900 dark:text-white">Chat Session Closed</p>
                        <p className="text-[11px] text-stone-500 dark:text-stone-400 mt-0.5">
                          {closedReason === 'inactivity_timeout'
                            ? 'This session was closed due to 10 minutes of inactivity.'
                            : 'This conversation has been closed.'}
                        </p>
                      </div>
                    </div>

                    <button
                      id="support-restart-chat-btn"
                      onClick={handleStartNewChat}
                      className="w-full py-2.5 px-4 rounded-xl bg-stone-900 hover:bg-black dark:bg-white dark:hover:bg-stone-100 text-white dark:text-stone-900 font-bold text-xs transition flex items-center justify-center gap-2 shadow-xs cursor-pointer"
                    >
                      <PlusCircle size={15} />
                      <span>Start New Conversation</span>
                    </button>
                  </div>
                ) : (
                  <div className="p-3 bg-white dark:bg-stone-900 border-t border-stone-200/80 dark:border-stone-800 flex-shrink-0">
                    {attachmentData && (
                      <div className="mb-2 relative inline-block">
                        <img src={attachmentData} alt="attachment" className="h-16 w-16 object-cover rounded-xl border border-stone-200 dark:border-stone-700 shadow-sm" />
                        <button
                          onClick={clearAttachment}
                          className="absolute -top-1.5 -right-1.5 bg-stone-900 text-white p-0.5 rounded-full hover:bg-black transition"
                        >
                          <X size={12} />
                        </button>
                      </div>
                    )}
                    <div className="flex items-end gap-1.5 bg-stone-100/90 dark:bg-stone-950 rounded-2xl p-1.5 border border-stone-200/90 dark:border-stone-800 focus-within:border-stone-900 dark:focus-within:border-stone-100 transition">
                      <input
                        type="file"
                        accept="image/*"
                        className="hidden"
                        ref={fileInputRef}
                        onChange={handleFileSelect}
                      />
                      <button
                        type="button"
                        onClick={() => fileInputRef.current?.click()}
                        className="p-2 text-stone-400 hover:text-stone-600 dark:hover:text-stone-200 transition rounded-xl cursor-pointer"
                        title="Attach image or receipt proof"
                      >
                        <Paperclip size={17} />
                      </button>
                      
                      <button
                        type="button"
                        onClick={() => setShowEmojiPicker(!showEmojiPicker)}
                        className="p-2 text-stone-400 hover:text-stone-600 dark:hover:text-stone-200 transition rounded-xl cursor-pointer"
                        title="Insert emoji"
                      >
                        <Smile size={17} />
                      </button>

                      <textarea
                        id="support-chat-input"
                        ref={textareaRef}
                        value={inputValue}
                        onChange={handleTextareaInput}
                        onKeyDown={handleKeyDown}
                        placeholder="Write a message..."
                        rows={1}
                        className="flex-1 bg-transparent py-2 text-xs sm:text-sm text-stone-900 dark:text-white placeholder:text-stone-400 resize-none outline-none max-h-24 custom-scrollbar leading-relaxed"
                      />

                      <button
                        id="support-chat-send-btn"
                        onClick={() => handleSendMessage()}
                        disabled={!inputValue.trim() && !attachmentData}
                        className="w-8 h-8 rounded-xl bg-stone-900 hover:bg-black dark:bg-white dark:hover:bg-stone-100 text-white dark:text-stone-900 disabled:opacity-20 disabled:cursor-not-allowed transition flex items-center justify-center shrink-0 shadow-xs cursor-pointer"
                        title="Send message"
                      >
                        <Send size={14} />
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              /* ================= VIEW: FAQS & KNOWLEDGE BASE ================= */
              <div className="flex-1 flex flex-col min-h-0 bg-stone-50/40 dark:bg-stone-950 p-4 sm:p-5 overflow-y-auto custom-scrollbar">
                {/* Search Bar */}
                <div className="relative mb-3 flex-shrink-0">
                  <Search size={15} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-stone-400" />
                  <input
                    id="support-faq-search"
                    type="text"
                    value={faqSearch}
                    onChange={(e) => setFaqSearch(e.target.value)}
                    placeholder="Search articles & questions..."
                    className="w-full pl-9 pr-3.5 py-2.5 bg-white dark:bg-stone-900 rounded-xl border border-stone-200/90 dark:border-stone-800 text-xs text-stone-900 dark:text-white placeholder:text-stone-400 focus:outline-none focus:border-stone-900 dark:focus:border-stone-100 transition shadow-2xs"
                  />
                </div>

                {/* Category Pills */}
                <div className="flex items-center gap-1.5 overflow-x-auto no-scrollbar pb-2.5 mb-2 flex-shrink-0">
                  {faqCategories.map((cat) => (
                    <button
                      key={cat}
                      onClick={() => {
                        setSelectedFaqCategory(cat);
                        setExpandedFaq(null);
                      }}
                      className={`shrink-0 px-2.5 py-1 rounded-lg text-[11px] font-bold transition cursor-pointer ${
                        selectedFaqCategory === cat
                          ? 'bg-stone-900 text-white dark:bg-white dark:text-stone-900 shadow-2xs'
                          : 'bg-white dark:bg-stone-900 text-stone-600 dark:text-stone-400 hover:bg-stone-100 dark:hover:bg-stone-800 border border-stone-200/60 dark:border-stone-800'
                      }`}
                    >
                      {cat}
                    </button>
                  ))}
                </div>

                {/* FAQ List */}
                <div className="space-y-2 flex-1 overflow-y-auto custom-scrollbar">
                  {filteredFaqs.length === 0 ? (
                    <div className="py-8 text-center text-xs text-stone-400">
                      No matching questions found.
                    </div>
                  ) : (
                    filteredFaqs.map((faq, idx) => {
                      const isItemOpen = expandedFaq === idx;
                      return (
                        <div
                          key={idx}
                          className="rounded-2xl border border-stone-200/80 dark:border-stone-800 bg-white dark:bg-stone-900 shadow-2xs overflow-hidden"
                        >
                          <button
                            onClick={() => setExpandedFaq(isItemOpen ? null : idx)}
                            className="w-full p-3.5 text-left flex items-start justify-between gap-2 text-xs font-semibold text-stone-800 dark:text-stone-200 hover:text-stone-900 dark:hover:text-white transition cursor-pointer"
                          >
                            <div className="flex-1 min-w-0 pr-1">
                              <span className="block font-bold">{faq.q}</span>
                              <span className="inline-block mt-1 px-1.5 py-0.5 rounded text-[9px] font-semibold uppercase tracking-wider bg-stone-100 dark:bg-stone-800 text-stone-500 dark:text-stone-400">
                                {faq.category}
                              </span>
                            </div>
                            <ChevronDown
                              size={15}
                              className={`text-stone-400 transition-transform shrink-0 mt-0.5 ${isItemOpen ? 'rotate-180' : ''}`}
                            />
                          </button>

                          {isItemOpen && (
                            <div className="px-3.5 pb-3.5 text-xs text-stone-600 dark:text-stone-400 leading-relaxed border-t border-stone-100 dark:border-stone-800/80 pt-3 bg-stone-50/50 dark:bg-stone-950/50">
                              <p className="whitespace-pre-line">{faq.a}</p>
                              <button
                                onClick={() => {
                                  handleSendMessage(faq.q, faq.a);
                                  setActiveTab('chat');
                                }}
                                className="mt-3 text-[11px] font-bold text-stone-900 dark:text-white hover:underline flex items-center gap-1 cursor-pointer"
                              >
                                Ask in Live Chat <ArrowLeft size={11} className="rotate-180" />
                              </button>
                            </div>
                          )}
                        </div>
                      );
                    })
                  )}
                </div>

                {/* Direct Live Help Banner */}
                <div className="mt-3 p-3 rounded-2xl bg-stone-900 text-white dark:bg-stone-800 flex items-center justify-between text-xs shrink-0 shadow-sm">
                  <div>
                    <span className="font-bold block font-heading">Have a custom question?</span>
                    <span className="text-[11px] text-stone-300">Talk directly with our team.</span>
                  </div>
                  <button
                    onClick={() => setActiveTab('chat')}
                    className="px-3 py-1.5 rounded-xl bg-white text-stone-900 dark:bg-white dark:text-stone-900 font-bold hover:bg-stone-100 transition cursor-pointer shadow-xs"
                  >
                    Open Chat
                  </button>
                </div>
              </div>
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default SupportChat;
